version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: travel-db
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: YourStrong!Pass123
    ports:
      - "1433:1433"
    volumes:
      - travel_sql_data:/var/opt/mssql
    restart: always

  app:
    build: .
    container_name: travel-web-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__DefaultConnection: "Server=db;Database=TravelDB;User Id=sa;Password=YourStrong!Pass123;TrustServerCertificate=True;Encrypt=False;"
    restart: always

volumes:
  travel_sql_data:
